insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'title','标题','text','常规',200,'',NULL,0,0,'required','','','',1,1,1,null,1,1,0,0,'normal',1604564165,1600400002);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'subtitle','副标题','text','常规',200,'',NULL,0,0,'','','','',1,1,2,null,0,1,0,0,'normal',1604564165,1600400002);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'user_id','投稿人','selectpage','常规',10,0,'{\"type\":\"table\",\"url\":\"\",\"url-show-field\":\"\",\"url-key-field\":\"\",\"url-search-field\":\"\",\"table\":\"user\",\"show-field\":\"username\",\"key-field\":\"id\",\"search-field\":\"username,nickname\",\"and-or\":\"\",\"order-by\":\"\",\"param\":{\"custom\":{\"status\":\"normal\"}},\"pagination\":\"1\"}',0,0,'','需要安装用户中心插件','','',1,1,3,'{\"ext\":\"\",\"filesize\":\"\",\"filter_option\":\"\"}',0,0,0,0,'normal',1649942700,1649924031);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'flags','文档属性','selectpage','常规',100,'','{\"type\":\"table\",\"url\":\"\",\"url-show-field\":\"\",\"url-key-field\":\"\",\"url-search-field\":\"\",\"table\":\"flags\",\"show-field\":\"title\",\"key-field\":\"name\",\"search-field\":\"title\",\"and-or\":\"\",\"order-by\":\"weigh desc\",\"param\":{\"custom\":{\"status\":\"normal\"}},\"multiple\":\"1\",\"pagination\":\"1\",\"select-only\":\"1\",\"enable-lang\":\"1\"}',0,0,'','','','',1,1,4,'{\"ext\":\"\",\"filesize\":\"\",\"filter_option\":\"\"}',0,1,0,0,'normal',1649942700,1649924031);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'tags','TAG标签','text','常规',250,'',NULL,0,0,'','','','class=\"form-control selectpage\",data-show-field=\"title\",data-search-field=\"title\",data-key-field=\"title\",data-data=\"/tags/tags\",data-pagination=\"false\",data-multiple=\"true\"',1,1,6,NULL,0,1,0,0,'normal',1667096966,1667096966);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'thumb','封面图','image','常规',100,'',NULL,0,0,'','','','',1,1,3,null,1,1,0,0,'normal',1604564175,1600400154);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'price','价格','number','常规',10,'0',NULL,0,2,'','','','',1,1,4,null,1,0,0,1,'normal',1616492830,1616492650);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'diyname','自定义URL名','text','常规',100,'',NULL,0,0,'','用于地址栏访问的名称，支持字母,数字,-,_，若为空则采用文章ID','','',1,1,6,null,0,1,0,0,'normal',1604564165,1600400002);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'content','内容','editor','常规',0,'',NULL,0,0,'','','','',0,1,7,null,1,1,0,0,'normal',1604565377,1600410507);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'weigh','排序','number','常规',11,'100',NULL,0,0,'','','','',1,1,8,null,0,1,0,0,'normal',1604564047,1600401198);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'iscomment','允许评论','radio','常规',1,'1','{\"1\":\"允许\",\"0\":\"不允许\"}',0,0,'','需要安装评论插件','','',1,1,9,null,0,1,0,0,'normal',1604041706,1604041706);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'islogin','访问限制','radio','常规',1,'0','{\"1\":\"需要登录\",\"0\":\"无限制\"}',0,0,'','需要安装用户中心插件','','',1,1,10,null,0,1,0,0,'normal',1604041706,1604041706);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'status','状态','radio','常规',250,'normal','{\"normal\":\"\\u6b63\\u5e38\",\"hidden\":\"\\u7981\\u7528\",\"reject\":\"\\u62d2\\u7edd\",\"audit\":\"\\u5f85\\u5ba1\\u6838\"}',0,0,'','','','',1,1,11,null,0,1,0,0,'normal',1604041706,1604041706);

insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'seotitle','seo标题','text','SEO',200,'',NULL,0,0,'','seo标题，为空则使用文章标题','','',1,1,14,null,0,1,0,0,'normal',1604564378,1600400833);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'keywords','关键词','text','SEO',200,'',NULL,0,0,'','多关键词之间用英文逗号隔开','','',1,1,15,null,0,1,0,0,'normal',1604564378,1600400833);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'description','描述','textarea','SEO',250,'',NULL,0,0,'','','','',1,1,16,null,0,1,0,0,'normal',1603937358,1600400870);

insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'author','作者','text','其他',250,'小编',NULL,0,0,'','','','',1,1,17,null,0,1,0,0,'normal',1604561438,1604557612);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'jumplink','跳转链接','text','其他',255,'',NULL,0,0,'','设置文档跳转到外部链接','','',1,1,18,null,0,1,0,0,'normal',1604564165,1600400002);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'views','浏览量','number','其他',11,'0',NULL,0,0,'','','','',1,1,18,null,0,1,0,1,'normal',1604563975,1604561217);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'likes','点赞数','number','其他',11,'0',NULL,0,0,'','','','',1,1,19,null,0,1,0,1,'normal',1604563975,1604561217);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'dislikes','点踩数','number','其他',11,'0',NULL,0,0,'','','','',1,1,20,null,0,1,0,0,'normal',1604563975,1604561217);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'comments','评论数','number','其他',11,'0',NULL,0,0,'','','','',1,1,21,null,0,0,0,1,'normal',1604563975,1604561217);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'collection','收藏数','number','其他',11,'0',NULL,0,0,'','','','',1,1,22,null,0,0,0,1,'normal',1604563975,1604561217);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'publish_time','发布时间','datetime','其他',0,'',NULL,0,0,'','','','',1,1,23,null,0,1,0,1,'normal',1604563079,1600401003);
insert  into `@prefix@model_field` (`id`,`model_id`,`field_name`,`field_title`,`form_type`,`field_group`,`length`,`default_value`,`data_list`,`max_number`,`decimals`,`rules`,`tips`,`error_tips`,`extend`,`iscore`,`default_field`,`weigh`,`setting`,`user_auth`,`admin_auth`,`is_filter`,`is_order`,`status`,`update_time`,`create_time`) values (NULL,@model_id@,'show_tpl','内容模板','text','其他',100,'show.html',NULL,0,0,'','','','class=\"form-control selectpage\",data-select-only=\"true\",data-data=\"/cms.model/getTplName.html?type=show\",data-pagination=\"false\",data-key-field=\"name\"',1,1,24,null,0,1,0,0,'normal',1604561449,1600400927);